server:
  shutdown: graceful
springdoc:
  show-actuator: true
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.batch_size: 50
      hibernate.order_inserts: true
      hibernate.order_updates: true

  threads:
    virtual:
      enabled: true
