server:
  shutdown: graceful
springdoc:
  show-actuator: true
spring:
  datasource:
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate

  threads:
    virtual:
      enabled: true
