version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Tests
          command: gradle test
      - run:
          name: Analyze on SonarCloud
          command: gradle build sonar
      - store_test_results:
          path: build/test-results
          
workflows:
  main:
    jobs:
      - build:
          context: SonarCloud