name: Publish to Docker Hub

on:
  release:
    types:
      - created
  workflow_dispatch:

permissions: { }

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Publish
        env:
          DOCKER_HUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}
        run: ./gradlew bootBuildImage
      - name: Upload SBOM
        uses: anchore/sbom-action@v0.16.0
        with:
          image: tacascer/predix
